{% set version = "2.19" %}

package:
  name: mappy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mappy/mappy-{{ version }}.tar.gz
  sha256: cd46ea643d18d8901e379914b4a1266c16c799263695ba969cce0bd85e2fb3f9

build:
  skip: True  # [py >= 39]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - zlib
  run:
    - python
    - zlib

test:
  imports:
    - mappy

about:
  home: https://github.com/lh3/minimap2
  license: MIT
  summary: 'Minimap2 Python binding'
