{% set version = "2.20" %}

package:
  name: mappy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mappy/mappy-{{ version }}.tar.gz
  sha256: 00c8720783ac982b514b01b86349ede9809eeaccdf1328acb5a16dfeef51458b

build:
  skip: True  # [py >= 39]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - zlib
  run:
    - python
    - zlib

test:
  imports:
    - mappy

about:
  home: https://github.com/lh3/minimap2
  license: MIT
  summary: 'Minimap2 Python binding'
